    Database.implementation: MysqlDB
    Blobstore.implementation: DbBlobStore

    API.DefaultRouter: ApiCallRouterWithoutChecks

    Server.initialized: true
    Server.fleetspeak_enabled: true
    Server.fleetspeak_server: fleetspeak-admin:9091
    FleetspeakFrontend Context:
      Server.fleetspeak_message_listen_address: 0.0.0.0:11111

    Mysql.host: mysql-grr
    Mysql.port: 3306
    Mysql.database: grr
    Mysql.username: grr-user
    Mysql.password: grr-password
    Mysql.database_name: grr
    Mysql.database_username: grr-user
    Mysql.database_password: grr-password
    Mysql.flow_processing_threads_max: 20
  
    AdminUI.url: http://localhost:8000
    AdminUI.bind: 0.0.0.0
    AdminUI.headless: true
    AdminUI.use_precompiled_js: true
    AdminUI.csrf_secret_key: random_passphrase_123____PLEASE_REPLACE___

    Logging.domain: localhost
    Logging.verbose: true
    Logging.engines: file,stderr
    Logging.path: /grr
    Logging.filename: /grr/grr-server.log
    Monitoring.alert_email: grr-monitoring@localhost
    Monitoring.emergency_access_email: grr-emergency@localhost

    Client.executable_signing_public_key: |
      %(/config/public-key.pem|file)

    PrivateKeys.executable_signing_private_key: |
      %(/config/private-key.pem|file)



